### ISSUE TITLE
Example output

### ISSUE THREAD

**Issue by vincentcox** [nip403/Steganography-QR#1]
Hi there,

Is it possible to add an example of the output after using this tool?

**Comment by nip403** [comment]
The demo should now work, fixed some major bugs. Attatched are the default outputs, sorry for the inconvenience @vincentcox .
**Input:**
![default](https://user-images.githubusercontent.com/41174986/111039504-49feef80-8426-11eb-8c15-5c44fbcc56ed.png)

**QR code:**
![default-hidden-qr](https://user-images.githubusercontent.com/41174986/111039479-2e93e480-8426-11eb-88d8-3bc66984d526.png)

**Output:**
![default-hidden](https://user-images.githubusercontent.com/41174986/111039481-2f2c7b00-8426-11eb-8439-e020180e8037.png)

**Comment by vincentcox** [comment]
Hello there, thanks for the example! In the meantime I am using a different technique to hide QR codes in images
